### ISSUE TITLE
Error during loading the plugin without "use strict" in templateScriptToTemplateCache

### ISSUE THREAD

**Issue by van-koelljor** [DecisionTechnologies/karma-ng-template-preprocessor#1]
When running a test, a error during loading the karma-ng-template-preprocessor-plugin is occuring.

This is the error-log:
`ERROR [plugin]: Error during loading "[...]/node_modules/karma-ng-template-preprocessor" plugin:
  Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

This leads to ng-template-preprocessor not loading:
`ERROR [preprocess]: Can not load "ng-template", it is not registered!
  Perhaps you are missing some plugin?`

`"use strict";` in **templateScriptToTemplateCache.js** fixes this.

**Comment by FreshRob** [comment]
issue has been fixed sorry for the slow turn around
